"""create attendees table

Revision ID: 35c508f6a1a4
Revises: f98af3975032
Create Date: 2026-06-28 15:55:47.550316

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "35c508f6a1a4"
down_revision: str | None = "f98af3975032"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attendees",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("order_item_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("ticket_code", sa.String(length=50), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "check_in_status",
            sa.String(length=20),
            server_default=sa.text("'not_checked_in'"),
            nullable=False,
        ),
        sa.Column("checked_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checked_in_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "check_in_status IN ('not_checked_in', 'checked_in')",
            name="ck_attendees_check_in_status",
        ),
        sa.ForeignKeyConstraint(["checked_in_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["order_item_id"], ["order_items.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticket_code"),
    )
    op.create_index(
        "ix_attendees_event_checkin",
        "attendees",
        ["event_id", "check_in_status"],
        unique=False,
    )
    op.create_index("ix_attendees_event_id", "attendees", ["event_id"], unique=False)
    op.create_index("ix_attendees_user_id", "attendees", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_attendees_user_id", table_name="attendees")
    op.drop_index("ix_attendees_event_id", table_name="attendees")
    op.drop_index("ix_attendees_event_checkin", table_name="attendees")
    op.drop_table("attendees")
    # ### end Alembic commands ###
