"""add moderation_status to reviews

Revision ID: 5f2e8b959690
Revises: 4db3a67e2fae
Create Date: 2026-07-01 12:54:04.502724

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5f2e8b959690"
down_revision: str | None = "4db3a67e2fae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reviews",
        sa.Column(
            "moderation_status",
            sa.String(length=20),
            server_default=sa.text("'approved'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "moderation_status")
    # ### end Alembic commands ###
