"""create events table

Revision ID: b25dcbec1c22
Revises: 385ecf8e287d
Create Date: 2026-06-28 13:30:53.470134

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b25dcbec1c22"
down_revision: str | None = "385ecf8e287d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("slug", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("short_description", sa.String(length=500), nullable=True),
        sa.Column("venue_name", sa.String(length=200), nullable=True),
        sa.Column("venue_address", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("start_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "timezone",
            sa.String(length=50),
            server_default=sa.text("'UTC'"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'draft'"),
            nullable=False,
        ),
        sa.Column(
            "is_featured", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("max_capacity", sa.Integer(), nullable=True),
        sa.Column("cover_image_url", sa.String(length=500), nullable=True),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'cancelled', 'completed')",
            name="ck_events_status",
        ),
        sa.CheckConstraint(
            "end_datetime > start_datetime", name="ck_events_end_after_start"
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index("ix_events_category_id", "events", ["category_id"], unique=False)
    op.create_index("ix_events_city", "events", ["city"], unique=False)
    op.create_index(
        "ix_events_lat_lng", "events", ["latitude", "longitude"], unique=False
    )
    op.create_index(
        "ix_events_organization_id", "events", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_events_start_datetime", "events", ["start_datetime"], unique=False
    )
    op.create_index("ix_events_status", "events", ["status"], unique=False)
    op.create_index(
        "ix_events_status_start", "events", ["status", "start_datetime"], unique=False
    )
    op.create_index(
        "ix_events_tags", "events", ["tags"], unique=False, postgresql_using="gin"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_events_tags", table_name="events", postgresql_using="gin")
    op.drop_index("ix_events_status_start", table_name="events")
    op.drop_index("ix_events_status", table_name="events")
    op.drop_index("ix_events_start_datetime", table_name="events")
    op.drop_index("ix_events_organization_id", table_name="events")
    op.drop_index("ix_events_lat_lng", table_name="events")
    op.drop_index("ix_events_city", table_name="events")
    op.drop_index("ix_events_category_id", table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
