"""create ticket_types table

Revision ID: c289eed2d2e9
Revises: bddd371580e2
Create Date: 2026-06-28 15:01:46.599294

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c289eed2d2e9"
down_revision: str | None = "bddd371580e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticket_types",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "currency",
            sa.String(length=3),
            server_default=sa.text("'INR'"),
            nullable=False,
        ),
        sa.Column("quantity_total", sa.Integer(), nullable=False),
        sa.Column(
            "quantity_sold", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("sale_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sale_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "max_per_order", sa.Integer(), server_default=sa.text("10"), nullable=False
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("max_per_order > 0", name="ck_ticket_types_max_per_order"),
        sa.CheckConstraint("price >= 0", name="ck_ticket_types_price"),
        sa.CheckConstraint(
            "quantity_sold <= quantity_total", name="ck_ticket_types_not_oversold"
        ),
        sa.CheckConstraint("quantity_sold >= 0", name="ck_ticket_types_qty_sold"),
        sa.CheckConstraint("quantity_total > 0", name="ck_ticket_types_qty_total"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ticket_types_event_active",
        "ticket_types",
        ["event_id", "is_active"],
        unique=False,
    )
    op.create_index(
        "ix_ticket_types_event_id", "ticket_types", ["event_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ticket_types_event_id", table_name="ticket_types")
    op.drop_index("ix_ticket_types_event_active", table_name="ticket_types")
    op.drop_table("ticket_types")
    # ### end Alembic commands ###
