"""create organizations and organization_members tables

Revision ID: c44f5b4783ad
Revises: 7b48f1058945
Create Date: 2026-06-28 13:14:29.881399

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c44f5b4783ad"
down_revision: str | None = "7b48f1058945"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=False),
        sa.Column(
            "is_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("stripe_account_id", sa.String(length=255), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(
        "ix_organizations_created_by", "organizations", ["created_by"], unique=False
    )
    op.create_index(
        "ix_organizations_is_verified", "organizations", ["is_verified"], unique=False
    )
    op.create_table(
        "organization_members",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "role",
            sa.String(length=20),
            server_default=sa.text("'member'"),
            nullable=False,
        ),
        sa.Column("invited_email", sa.String(length=255), nullable=True),
        sa.Column("invitation_token", sa.String(length=255), nullable=True),
        sa.Column(
            "invitation_status",
            sa.String(length=20),
            server_default=sa.text("'accepted'"),
            nullable=False,
        ),
        sa.Column("invited_by", sa.UUID(), nullable=True),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "invitation_status IN ('pending', 'accepted', 'declined')",
            name="ck_org_members_invitation_status",
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'member')", name="ck_org_members_role"
        ),
        sa.ForeignKeyConstraint(["invited_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invitation_token"),
    )
    op.create_index(
        "ix_org_members_invited_email",
        "organization_members",
        ["invited_email"],
        unique=False,
    )
    op.create_index(
        "ix_org_members_user_id", "organization_members", ["user_id"], unique=False
    )
    op.create_index(
        "uq_org_members_org_user",
        "organization_members",
        ["organization_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_org_members_org_user",
        table_name="organization_members",
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.drop_index("ix_org_members_user_id", table_name="organization_members")
    op.drop_index("ix_org_members_invited_email", table_name="organization_members")
    op.drop_table("organization_members")
    op.drop_index("ix_organizations_is_verified", table_name="organizations")
    op.drop_index("ix_organizations_created_by", table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
